package usecase

import (
	"context"
	"fmt"
	"irfanard27/incore-api/internal/domain/entity"
	"irfanard27/incore-api/internal/domain/repository"
)

type InventoryUsecase interface {
	CreateInventory(ctx context.Context, sku, name string, price, quantity int) (*entity.Inventory, error)
	GetInventoryById(ctx context.Context, id string) (*entity.Inventory, error)
	GetAllInventories(ctx context.Context) ([]entity.Inventory, error)
	UpdateInventory(ctx context.Context, inventory *entity.Inventory) (*entity.Inventory, error)
	DeleteInventory(ctx context.Context, id string) error
	SearchInventory(ctx context.Context, keyword string) ([]entity.Inventory, error)
}

type inventoryUsecase struct {
	inventoryRepo repository.InventoryRepository
}

func NewInventoryUsecase(inventoryRepo repository.InventoryRepository) InventoryUsecase {
	return &inventoryUsecase{
		inventoryRepo: inventoryRepo,
	}
}

func (i *inventoryUsecase) GetAllInventories(ctx context.Context) ([]entity.Inventory, error) {
	inventories, err := i.inventoryRepo.All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get all inventories: %w", err)
	}
	return inventories, nil
}

func (i *inventoryUsecase) SearchInventory(ctx context.Context, keyword string) ([]entity.Inventory, error) {
	inventories, err := i.inventoryRepo.Search(ctx, keyword)
	if err != nil {
		return nil, fmt.Errorf("failed to search inventories: %w", err)
	}
	return inventories, nil
}

func (i *inventoryUsecase) GetInventoryById(ctx context.Context, id string) (*entity.Inventory, error) {
	inventory, err := i.inventoryRepo.GetById(ctx, id)

	if err != nil {
		return nil, fmt.Errorf("failed to get inventory by id: %w", err)
	}
	return inventory, nil
}

func (i *inventoryUsecase) CreateInventory(ctx context.Context, sku, name string, price, quantity int) (*entity.Inventory, error) {
	// Create new inventory - ID will be generated by database
	inventory := &entity.Inventory{
		Sku:      sku,
		Name:     name,
		Price:    price,
		Quantity: quantity,
	}

	err := i.inventoryRepo.Create(ctx, inventory)
	if err != nil {
		return nil, fmt.Errorf("failed to create inventory: %w", err)
	}

	return inventory, nil
}

func (i *inventoryUsecase) UpdateInventory(ctx context.Context, inventory *entity.Inventory) (*entity.Inventory, error) {
	// First check if inventory exists
	existingInventory, err := i.inventoryRepo.GetById(ctx, inventory.ID)
	if err != nil {
		return nil, fmt.Errorf("inventory not found: %w", err)
	}

	// Update inventory
	inventory.ID = existingInventory.ID

	err = i.inventoryRepo.Update(ctx, inventory)
	if err != nil {
		return nil, fmt.Errorf("failed to update inventory: %w", err)
	}

	return existingInventory, nil
}

func (i *inventoryUsecase) DeleteInventory(ctx context.Context, id string) error {
	// First check if inventory exists
	_, err := i.inventoryRepo.GetById(ctx, id)
	if err != nil {
		return fmt.Errorf("inventory not found: %w", err)
	}

	err = i.inventoryRepo.Delete(ctx, id)
	if err != nil {
		return fmt.Errorf("failed to delete inventory: %w", err)
	}

	return nil
}
