package usecase

import (
	"context"
	"fmt"
	"irfanard27/incore-api/internal/domain/entity"
	"irfanard27/incore-api/internal/domain/repository"
	"time"
)

type StockInItemUsecase interface {
	CreateStockInItem(ctx context.Context, stockInID, inventoryID string, quantity int) (*entity.StockInItem, error)
	GetStockInItemById(ctx context.Context, id string) (*entity.StockInItem, error)
	GetStockInItemsByStockInID(ctx context.Context, stockInID string) ([]entity.StockInItem, error)
	GetAllStockInItems(ctx context.Context) ([]entity.StockInItem, error)
	UpdateStockInItem(ctx context.Context, id string, stockInID, inventoryID string, quantity int) (*entity.StockInItem, error)
	DeleteStockInItem(ctx context.Context, id string) error
}

type stockInItemUsecase struct {
	stockInItemRepo repository.StockInItemRepository
}

func NewStockInItemUsecase(stockInItemRepo repository.StockInItemRepository) StockInItemUsecase {
	return &stockInItemUsecase{
		stockInItemRepo: stockInItemRepo,
	}
}

func (s *stockInItemUsecase) CreateStockInItem(ctx context.Context, stockInID, inventoryID string, quantity int) (*entity.StockInItem, error) {
	// Validate quantity
	if quantity <= 0 {
		return nil, fmt.Errorf("quantity must be greater than 0")
	}

	// Create new stock in item - ID will be generated by database
	stockInItem := &entity.StockInItem{
		ID:          "", // Will be set by database
		StockInID:   stockInID,
		InventoryID: inventoryID,
		Quantity:    quantity,
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	}

	err := s.stockInItemRepo.Create(ctx, stockInItem)
	if err != nil {
		return nil, fmt.Errorf("failed to create stock in item: %w", err)
	}

	return stockInItem, nil
}

func (s *stockInItemUsecase) GetStockInItemById(ctx context.Context, id string) (*entity.StockInItem, error) {
	stockInItem, err := s.stockInItemRepo.GetById(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get stock in item by id: %w", err)
	}
	return stockInItem, nil
}

func (s *stockInItemUsecase) GetStockInItemsByStockInID(ctx context.Context, stockInID string) ([]entity.StockInItem, error) {
	stockInItems, err := s.stockInItemRepo.GetByStockInID(ctx, stockInID)
	if err != nil {
		return nil, fmt.Errorf("failed to get stock in items by stock in id: %w", err)
	}
	return stockInItems, nil
}

func (s *stockInItemUsecase) GetAllStockInItems(ctx context.Context) ([]entity.StockInItem, error) {
	stockInItems, err := s.stockInItemRepo.All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get all stock in items: %w", err)
	}
	return stockInItems, nil
}

func (s *stockInItemUsecase) UpdateStockInItem(ctx context.Context, id string, stockInID, inventoryID string, quantity int) (*entity.StockInItem, error) {
	// Validate quantity
	if quantity <= 0 {
		return nil, fmt.Errorf("quantity must be greater than 0")
	}

	// First check if stock in item exists
	existingStockInItem, err := s.stockInItemRepo.GetById(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("stock in item not found: %w", err)
	}

	// Update stock in item
	existingStockInItem.StockInID = stockInID
	existingStockInItem.InventoryID = inventoryID
	existingStockInItem.Quantity = quantity
	existingStockInItem.UpdatedAt = time.Now()

	err = s.stockInItemRepo.Update(ctx, existingStockInItem)
	if err != nil {
		return nil, fmt.Errorf("failed to update stock in item: %w", err)
	}

	return existingStockInItem, nil
}

func (s *stockInItemUsecase) DeleteStockInItem(ctx context.Context, id string) error {
	// First check if stock in item exists
	_, err := s.stockInItemRepo.GetById(ctx, id)
	if err != nil {
		return fmt.Errorf("stock in item not found: %w", err)
	}

	err = s.stockInItemRepo.Delete(ctx, id)
	if err != nil {
		return fmt.Errorf("failed to delete stock in item: %w", err)
	}

	return nil
}
