package usecase

import (
	"context"
	"fmt"
	"irfanard27/incore-api/internal/domain/entity"
	"irfanard27/incore-api/internal/domain/repository"
	"time"
)

type StockInUsecase interface {
	CreateStockIn(ctx context.Context, items []entity.StockInItem) (*entity.StockIn, error)
	GetStockInById(ctx context.Context, id string) (*entity.StockIn, []entity.StockInItem, []entity.Inventory, error)
	GetStockInByTransactionID(ctx context.Context, transactionID string) (*entity.StockIn, error)
	GetAllStockIn(ctx context.Context) ([]entity.StockIn, error)
	UpdateStockIn(ctx context.Context, id string, transactionID, status string) (*entity.StockIn, error)
	UpdateStatusToInProgress(ctx context.Context, id string) (*entity.StockIn, error)
	UpdateStatusToDone(ctx context.Context, id string) (*entity.StockIn, error)
	DeleteStockIn(ctx context.Context, id string) error
}

type stockInUsecase struct {
	stockInRepo     repository.StockInRepository
	stockInItemRepo repository.StockInItemRepository
	inventoryRepo   repository.InventoryRepository
}

func NewStockInUsecase(stockInRepo repository.StockInRepository, stockInItemRepo repository.StockInItemRepository, inventoryRepo repository.InventoryRepository) StockInUsecase {
	return &stockInUsecase{
		stockInRepo:     stockInRepo,
		stockInItemRepo: stockInItemRepo,
		inventoryRepo:   inventoryRepo,
	}
}

func (s *stockInUsecase) GetAllStockIn(ctx context.Context) ([]entity.StockIn, error) {
	stockIns, err := s.stockInRepo.All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get all stock ins: %w", err)
	}
	return stockIns, nil
}

func (s *stockInUsecase) CreateStockIn(ctx context.Context, items []entity.StockInItem) (*entity.StockIn, error) {

	if len(items) == 0 {
		return nil, fmt.Errorf("items must be provided")
	}

	// Create new stock in - ID will be generated by database
	stockIn := &entity.StockIn{
		TransactionID: generateTransactionID(),
	}

	id, err := s.stockInRepo.Create(ctx, stockIn)
	if err != nil {
		return nil, fmt.Errorf("failed to create stock in: %w", err)
	}

	// Set the ID returned from repository
	stockIn.ID = id

	// Set stock_in_id for each item before batch create
	for i := range items {
		items[i].StockInID = id
	}

	err = s.stockInItemRepo.BatchCreate(ctx, items)
	if err != nil {
		return nil, fmt.Errorf("failed to batch create stock in items: %w", err)
	}

	return stockIn, nil
}

func (s *stockInUsecase) GetStockInById(ctx context.Context, id string) (*entity.StockIn, []entity.StockInItem, []entity.Inventory, error) {
	stockIn, err := s.stockInRepo.GetById(ctx, id)
	if err != nil {
		return nil, nil, nil, fmt.Errorf("failed to get stock in by id: %w", err)
	}

	items, inventories, err := s.stockInItemRepo.GetByStockInIDWithInventory(ctx, id)
	if err != nil {
		return nil, nil, nil, fmt.Errorf("failed to get stock in items: %w", err)
	}

	return stockIn, items, inventories, nil
}

func (s *stockInUsecase) GetStockInByTransactionID(ctx context.Context, transactionID string) (*entity.StockIn, error) {
	stockIn, err := s.stockInRepo.GetByTransactionID(ctx, transactionID)
	if err != nil {
		return nil, fmt.Errorf("failed to get stock in by transaction id: %w", err)
	}
	return stockIn, nil
}

func (s *stockInUsecase) UpdateStockIn(ctx context.Context, id string, transactionID, status string) (*entity.StockIn, error) {
	// First check if stock in exists
	existingStockIn, err := s.stockInRepo.GetById(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("stock in not found: %w", err)
	}

	// Update stock in
	existingStockIn.TransactionID = transactionID
	existingStockIn.Status = status
	existingStockIn.UpdatedAt = time.Now()

	err = s.stockInRepo.Update(ctx, existingStockIn)
	if err != nil {
		return nil, fmt.Errorf("failed to update stock in: %w", err)
	}

	return existingStockIn, nil
}

func (s *stockInUsecase) UpdateStatusToInProgress(ctx context.Context, id string) (*entity.StockIn, error) {
	// First check if stock in exists and validate current status
	existingStockIn, err := s.stockInRepo.GetById(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("stock in not found: %w", err)
	}

	// Validate that current status is 'created' before updating to 'in_progress'
	if existingStockIn.Status != "created" {
		return nil, fmt.Errorf("cannot update status to in_progress: current status is '%s', expected 'created'", existingStockIn.Status)
	}

	// Update status to in_progress
	existingStockIn.Status = "in_progress"
	existingStockIn.UpdatedAt = time.Now()

	err = s.stockInRepo.Update(ctx, existingStockIn)
	if err != nil {
		return nil, fmt.Errorf("failed to update stock in status: %w", err)
	}

	return existingStockIn, nil
}

func (s *stockInUsecase) UpdateStatusToDone(ctx context.Context, id string) (*entity.StockIn, error) {
	// First check if stock in exists and validate current status
	existingStockIn, err := s.stockInRepo.GetById(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("stock in not found: %w", err)
	}

	// Validate that current status is 'in_progress' before updating to 'done'
	if existingStockIn.Status != "in_progress" {
		return nil, fmt.Errorf("cannot update status to done: current status is '%s', expected 'in_progress'", existingStockIn.Status)
	}

	// Get all stock in items for this stock in
	stockInItems, err := s.stockInItemRepo.GetByStockInID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get stock in items: %w", err)
	}

	// Update inventory quantities for each item
	for _, item := range stockInItems {
		// Get the current inventory
		inventory, err := s.inventoryRepo.GetById(ctx, item.InventoryID)
		if err != nil {
			return nil, fmt.Errorf("failed to get inventory %s: %w", item.InventoryID, err)
		}

		// Update inventory quantity
		inventory.Quantity += item.Quantity

		// Save the updated inventory
		err = s.inventoryRepo.Update(ctx, inventory)
		if err != nil {
			return nil, fmt.Errorf("failed to update inventory quantity for %s: %w", item.InventoryID, err)
		}
	}

	// Update stock in status to done
	existingStockIn.Status = "done"
	existingStockIn.UpdatedAt = time.Now()

	err = s.stockInRepo.Update(ctx, existingStockIn)
	if err != nil {
		return nil, fmt.Errorf("failed to update stock in status: %w", err)
	}

	return existingStockIn, nil
}

func (s *stockInUsecase) DeleteStockIn(ctx context.Context, id string) error {
	// First check if stock in exists
	_, err := s.stockInRepo.GetById(ctx, id)
	if err != nil {
		return fmt.Errorf("stock in not found: %w", err)
	}

	err = s.stockInRepo.Delete(ctx, id)
	if err != nil {
		return fmt.Errorf("failed to delete stock in: %w", err)
	}

	return nil
}

func generateTransactionID() string {
	return "STI-" + time.Now().Format("20060102150405")
}
