package usecase

import (
	"context"
	"fmt"
	"irfanard27/incore-api/internal/domain/entity"
	"irfanard27/incore-api/internal/domain/repository"
	"time"
)

type StockOutItemUsecase interface {
	CreateStockOutItem(ctx context.Context, stockOutID, inventoryID string, quantity int) (*entity.StockOutItem, error)
	GetStockOutItemById(ctx context.Context, id string) (*entity.StockOutItem, error)
	GetStockOutItemsByStockOutID(ctx context.Context, stockOutID string) ([]entity.StockOutItem, error)
	GetAllStockOutItems(ctx context.Context) ([]entity.StockOutItem, error)
	UpdateStockOutItem(ctx context.Context, id string, stockOutID, inventoryID string, quantity int) (*entity.StockOutItem, error)
	DeleteStockOutItem(ctx context.Context, id string) error
}

type stockOutItemUsecase struct {
	stockOutItemRepo repository.StockOutItemRepository
}

func NewStockOutItemUsecase(stockOutItemRepo repository.StockOutItemRepository) StockOutItemUsecase {
	return &stockOutItemUsecase{
		stockOutItemRepo: stockOutItemRepo,
	}
}

func (s *stockOutItemUsecase) CreateStockOutItem(ctx context.Context, stockOutID, inventoryID string, quantity int) (*entity.StockOutItem, error) {
	// Validate quantity
	if quantity <= 0 {
		return nil, fmt.Errorf("quantity must be greater than 0")
	}

	// Create new stock out item - ID will be generated by database
	stockOutItem := &entity.StockOutItem{
		ID:           "", // Will be set by database
		StockOutID:   stockOutID,
		InventoryID:  inventoryID,
		Quantity:     quantity,
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
	}

	err := s.stockOutItemRepo.Create(ctx, stockOutItem)
	if err != nil {
		return nil, fmt.Errorf("failed to create stock out item: %w", err)
	}

	return stockOutItem, nil
}

func (s *stockOutItemUsecase) GetStockOutItemById(ctx context.Context, id string) (*entity.StockOutItem, error) {
	stockOutItem, err := s.stockOutItemRepo.GetById(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get stock out item by id: %w", err)
	}
	return stockOutItem, nil
}

func (s *stockOutItemUsecase) GetStockOutItemsByStockOutID(ctx context.Context, stockOutID string) ([]entity.StockOutItem, error) {
	stockOutItems, err := s.stockOutItemRepo.GetByStockOutID(ctx, stockOutID)
	if err != nil {
		return nil, fmt.Errorf("failed to get stock out items by stock out id: %w", err)
	}
	return stockOutItems, nil
}

func (s *stockOutItemUsecase) GetAllStockOutItems(ctx context.Context) ([]entity.StockOutItem, error) {
	stockOutItems, err := s.stockOutItemRepo.All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get all stock out items: %w", err)
	}
	return stockOutItems, nil
}

func (s *stockOutItemUsecase) UpdateStockOutItem(ctx context.Context, id string, stockOutID, inventoryID string, quantity int) (*entity.StockOutItem, error) {
	// Validate quantity
	if quantity <= 0 {
		return nil, fmt.Errorf("quantity must be greater than 0")
	}

	// First check if stock out item exists
	existingStockOutItem, err := s.stockOutItemRepo.GetById(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("stock out item not found: %w", err)
	}

	// Update stock out item
	existingStockOutItem.StockOutID = stockOutID
	existingStockOutItem.InventoryID = inventoryID
	existingStockOutItem.Quantity = quantity
	existingStockOutItem.UpdatedAt = time.Now()

	err = s.stockOutItemRepo.Update(ctx, existingStockOutItem)
	if err != nil {
		return nil, fmt.Errorf("failed to update stock out item: %w", err)
	}

	return existingStockOutItem, nil
}

func (s *stockOutItemUsecase) DeleteStockOutItem(ctx context.Context, id string) error {
	// First check if stock out item exists
	_, err := s.stockOutItemRepo.GetById(ctx, id)
	if err != nil {
		return fmt.Errorf("stock out item not found: %w", err)
	}

	err = s.stockOutItemRepo.Delete(ctx, id)
	if err != nil {
		return fmt.Errorf("failed to delete stock out item: %w", err)
	}

	return nil
}
