package usecase

import (
	"context"
	"fmt"
	"irfanard27/incore-api/internal/domain/entity"
	"irfanard27/incore-api/internal/domain/repository"
	"time"
)

type StockInUsecase interface {
	CreateStockIn(ctx context.Context, items []entity.StockInItem) (*entity.StockIn, error)
	GetStockInById(ctx context.Context, id string) (*entity.StockIn, error)
	GetStockInByTransactionID(ctx context.Context, transactionID string) (*entity.StockIn, error)
	GetAllStockIn(ctx context.Context) ([]entity.StockIn, error)
	UpdateStockIn(ctx context.Context, id string, transactionID, status string) (*entity.StockIn, error)
	DeleteStockIn(ctx context.Context, id string) error
}

type stockInUsecase struct {
	stockInRepo     repository.StockInRepository
	stockInItemRepo repository.StockInItemRepository
}

func NewStockInUsecase(stockInRepo repository.StockInRepository, stockInItemRepo repository.StockInItemRepository) StockInUsecase {
	return &stockInUsecase{
		stockInRepo:     stockInRepo,
		stockInItemRepo: stockInItemRepo,
	}
}

func (s *stockInUsecase) CreateStockIn(ctx context.Context, items []entity.StockInItem) (*entity.StockIn, error) {

	if len(items) == 0 {
		return nil, fmt.Errorf("items must be provided")
	}

	// Create new stock in - ID will be generated by database
	stockIn := &entity.StockIn{
		TransactionID: generateTransactionID(),
	}

	id, err := s.stockInRepo.Create(ctx, stockIn)
	if err != nil {
		return nil, fmt.Errorf("failed to create stock in: %w", err)
	}

	// Set the ID returned from repository
	stockIn.ID = id

	// Set stock_in_id for each item before batch create
	for i := range items {
		items[i].StockInID = id
	}

	err = s.stockInItemRepo.BatchCreate(ctx, items)
	if err != nil {
		return nil, fmt.Errorf("failed to batch create stock in items: %w", err)
	}

	return stockIn, nil
}

func (s *stockInUsecase) GetStockInById(ctx context.Context, id string) (*entity.StockIn, error) {
	stockIn, err := s.stockInRepo.GetById(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get stock in by id: %w", err)
	}
	return stockIn, nil
}

func (s *stockInUsecase) GetStockInByTransactionID(ctx context.Context, transactionID string) (*entity.StockIn, error) {
	stockIn, err := s.stockInRepo.GetByTransactionID(ctx, transactionID)
	if err != nil {
		return nil, fmt.Errorf("failed to get stock in by transaction id: %w", err)
	}
	return stockIn, nil
}

func (s *stockInUsecase) GetAllStockIn(ctx context.Context) ([]entity.StockIn, error) {
	stockIns, err := s.stockInRepo.All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get all stock ins: %w", err)
	}
	return stockIns, nil
}

func (s *stockInUsecase) UpdateStockIn(ctx context.Context, id string, transactionID, status string) (*entity.StockIn, error) {
	// First check if stock in exists
	existingStockIn, err := s.stockInRepo.GetById(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("stock in not found: %w", err)
	}

	// Update stock in
	existingStockIn.TransactionID = transactionID
	existingStockIn.Status = status
	existingStockIn.UpdatedAt = time.Now()

	err = s.stockInRepo.Update(ctx, existingStockIn)
	if err != nil {
		return nil, fmt.Errorf("failed to update stock in: %w", err)
	}

	return existingStockIn, nil
}

func (s *stockInUsecase) DeleteStockIn(ctx context.Context, id string) error {
	// First check if stock in exists
	_, err := s.stockInRepo.GetById(ctx, id)
	if err != nil {
		return fmt.Errorf("stock in not found: %w", err)
	}

	err = s.stockInRepo.Delete(ctx, id)
	if err != nil {
		return fmt.Errorf("failed to delete stock in: %w", err)
	}

	return nil
}

func generateTransactionID() string {
	return "STI-" + time.Now().Format("20060102150405")
}
