package usecase

import (
	"context"
	"fmt"
	"irfanard27/incore-api/internal/domain/entity"
	"irfanard27/incore-api/internal/domain/repository"
	"time"
)

type StockOutUsecase interface {
	CreateStockOut(ctx context.Context, transactionID string) (*entity.StockOut, error)
	GetStockOutById(ctx context.Context, id string) (*entity.StockOut, error)
	GetStockOutByTransactionID(ctx context.Context, transactionID string) (*entity.StockOut, error)
	GetAllStockOut(ctx context.Context) ([]entity.StockOut, error)
	UpdateStockOut(ctx context.Context, id string, transactionID, status string) (*entity.StockOut, error)
	DeleteStockOut(ctx context.Context, id string) error
}

type stockOutUsecase struct {
	stockOutRepo repository.StockOutRepository
}

func NewStockOutUsecase(stockOutRepo repository.StockOutRepository) StockOutUsecase {
	return &stockOutUsecase{
		stockOutRepo: stockOutRepo,
	}
}

func (s *stockOutUsecase) CreateStockOut(ctx context.Context, transactionID string) (*entity.StockOut, error) {
	// Check if transaction ID already exists
	existingStockOut, err := s.stockOutRepo.GetByTransactionID(ctx, transactionID)
	if err == nil && existingStockOut != nil {
		return nil, fmt.Errorf("stock out with transaction ID %s already exists", transactionID)
	}

	// Create new stock out - ID will be generated by database
	stockOut := &entity.StockOut{
		ID:            "", // Will be set by database
		TransactionID: transactionID,
		Status:        "pending", // Default status
		CreatedAt:     time.Now(),
		UpdatedAt:     time.Now(),
	}

	err = s.stockOutRepo.Create(ctx, stockOut)
	if err != nil {
		return nil, fmt.Errorf("failed to create stock out: %w", err)
	}

	return stockOut, nil
}

func (s *stockOutUsecase) GetStockOutById(ctx context.Context, id string) (*entity.StockOut, error) {
	stockOut, err := s.stockOutRepo.GetById(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get stock out by id: %w", err)
	}
	return stockOut, nil
}

func (s *stockOutUsecase) GetStockOutByTransactionID(ctx context.Context, transactionID string) (*entity.StockOut, error) {
	stockOut, err := s.stockOutRepo.GetByTransactionID(ctx, transactionID)
	if err != nil {
		return nil, fmt.Errorf("failed to get stock out by transaction id: %w", err)
	}
	return stockOut, nil
}

func (s *stockOutUsecase) GetAllStockOut(ctx context.Context) ([]entity.StockOut, error) {
	stockOuts, err := s.stockOutRepo.All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get all stock outs: %w", err)
	}
	return stockOuts, nil
}

func (s *stockOutUsecase) UpdateStockOut(ctx context.Context, id string, transactionID, status string) (*entity.StockOut, error) {
	// First check if stock out exists
	existingStockOut, err := s.stockOutRepo.GetById(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("stock out not found: %w", err)
	}

	// Update stock out
	existingStockOut.TransactionID = transactionID
	existingStockOut.Status = status
	existingStockOut.UpdatedAt = time.Now()

	err = s.stockOutRepo.Update(ctx, existingStockOut)
	if err != nil {
		return nil, fmt.Errorf("failed to update stock out: %w", err)
	}

	return existingStockOut, nil
}

func (s *stockOutUsecase) DeleteStockOut(ctx context.Context, id string) error {
	// First check if stock out exists
	_, err := s.stockOutRepo.GetById(ctx, id)
	if err != nil {
		return fmt.Errorf("stock out not found: %w", err)
	}

	err = s.stockOutRepo.Delete(ctx, id)
	if err != nil {
		return fmt.Errorf("failed to delete stock out: %w", err)
	}

	return nil
}
